version: '2.1'
services:
  web:
    container_name: annuityService
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/data/annuityservice


