openapi: 3.0.0

info:
  title: Recht API
  description: Recht administratie service
  version: "1.0"

servers:
  - url: http://localhost:8080
    description: "Development server"

tags:
  - name: Annuity
    description: Annuity REST API

security:
  - BearerAuth: [ ]

paths:
  /annuity/repayment:
    post:
      operationId: getRepaymentSchedule
      summary: Get repayment schedule for a given loan.
      description: " Get repayment schedule for a given loan."
      tags:
        - Repayment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: Loan2
      responses:
        '200':
          description:
          headers:
            location:
              schema:
                type: string
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/ServerError'
components:
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ServerError:
      description: Server side problem
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    Loan2:
      type: object
      title: Loan
      description: The loan
      required:
        - initialLoan
        - annualInterestPercentage
        - periodicity
        - startDate
        - timing
        - loanTermInMonths
      properties:
        initialLoan:
          type: number
          description: Type van het recht
        annualInterestPercentage:
          type: number
          description: Type van het recht
        startDate:
          type: string
          format: date
          description: The start date of the loan
        endDate:
          type: string
          format: date
          description: The end date of the loan
        loanTermInMonths:
          type: integer
          description: Test
        periodicity:
          type: Periodicity
        timing:
          type: Timing
    ErrorResponse:
      type: object
      title: Error response
      description: Error response attributen
      properties:
        reason:
          type: string
          description: Foutmelding
        reference:
          type: string
          format: uuid
          description: Reference UUID